spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://localhost:3306/winery_spring_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
logging:
  level: 
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
  pattern:
    level:
server:
  port: 8022

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/**
      cache:
        period: 0

        server:
          tomcat:
            uri-encoding=UTF-8:
  mail:
    host: smtp.gmail.com
    port: 578
    username: ${email_username}
    password: ${password_email}
    test-connection: true

    properties:
      mail:
        smtp:
          auth=true:

            properties:
              mail:
                smtp:
                  starttls:
                    enable=true:
                        connectiontimeout: 5000  # Максимално време за изчакване на свързване (в милисекунди)
                        timeout: 5000            # Максимално време за отговор
                        writetimeout: 5000


HistoryAppNew:
  default.admin.pass: ${default.admin.pass}
  remember.me.key: ${remember.me.key}

#shift:
#  ancient_images: greek.jpeg, changeImage1.png, changeImage2.jpg, sphinks2.jpg
#  refresh-cron: "0 */10 * * * *"

recaptcha:
secret: ${secret_key}
site: ${site_key}
brand-service:
  base-url: http://localhost:8022

cloudinary:
  name: ${CLOUDINARY_NAME:dy2y8i2de}
  api-key: ${CLOUDINARY_API_KEY:111187215981859}
  api-secret: ${CLOUDINARY_API_SECRET:H3gM21c_0mYpOPklNO3pR11s8HE}




jwt:
  secret: ${jwt.secret:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}
  expiration: ${jwt.expiration:58000}

user.deletion: P300D

log:
  deletion: P30D

offers:
  api:
    baseUrl: "http//localhost:8022"

After 3 years of frustration here is a solution for a working HOT SWAP:

  https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates
  
  Below are my tested settings (this is the only thing I've changed for it to work).

application.yaml:

